import Head from 'next/head'
import ImageFrame from '../components/ImageFrame'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Image Search App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageFrame />
    </div>
  )
}
